[tool.poetry]
name = "api"
version = "0.1.0"
description = ""
authors = ["Joshua Price <git@jprice.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
boto3 = "^1.35.26"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
