name: Website deployment
run-name: Deploying website to S3 bucket 🚀
on: [push]
jobs:
  Deployment:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: S3 Deploy
        uses: Reggionick/s3-deploy@v4.0.0
        with:
          folder: dist
          bucket: 'qmbank.uk'
          bucket-region: eu-west-2
          dist-id: E4QQXWE3WTUDW
          delete-removed: true
